upstream booking_service {
    server booking:3001;
}

upstream identity_service {
    server identity:3002;
}

upstream catalog_service {
    server catalog:3003;
}

server {
    listen 80;
    server_name localhost;
    
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location = /users {
        proxy_pass http://identity_service/;
    }

    location /users/ {
        proxy_pass http://identity_service/;
    }

    location /hall {
        proxy_pass http://catalog_service;
    }

    location /movie {
        proxy_pass http://catalog_service;
    }

    location /session {
        proxy_pass http://catalog_service;
    }

    location = /tickets {
        proxy_pass http://booking_service/;
    }

    location /tickets/ {
        proxy_pass http://booking_service/;
    }

    location / {
        return 404 "Service not found"; 
    }
}