apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cb

resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - postgres.yaml
  - mongodb.yaml
  - rabbitmq.yaml
  - booking-deployment.yaml
  - identity-deployment.yaml
  - catalog-deployment.yaml
  - notifications-deployment.yaml
  - ingress.yaml
