apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: password
  postgres-db: cinema-booking
  mongo-user: admin
  mongo-password: password123
  rabbitmq-user: user
  rabbitmq-password: password
  jwt-secret: jwt_secret
  stripe-secret: sk_test
  nodemailer-token: nodemailer_token
